quarkus:
  application:
    name: books-api

  log:
    level: INFO
    category:
      "com.jeremw.bookstore":
        level: DEBUG
  native:
    resources:
      includes:
        publicKey: publicKey.pem

  hibernate-orm:
    database:
      generation: drop-and-create

  smallrye-openapi:
    info-title: Books API
    info-description: This API allows CRUD operations on a books
    info-version: 1.0
    info-contact-name: Jérémy Woirhaye
  http:
    cors:
      ~: true
      origins: "*"
      access-control-allow-credentials: true

mp:
  jwt:
    verify:
      publickey:
        location: publicKey.pem
    issuer: https://example.com/issuer


smallrye:
  jwt:
    sign:
      key:
        location: privateKey.pem

auth:
  jwt:
    access-token:
      expiration: 60000
  password:
    secret: secret
    iteration: 33
    key-length: 256