version: "3"
services:
  books-db:
    image: postgres:alpine
    container_name: books-db
    ports:
      - "5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: books_database


  books-api-java17:
    image: books-api-java17:latest
    container_name: books-api-java17
    build:
      context: ../../
      dockerfile: src/main/docker/Dockerfile.jvm
    depends_on:
      - books-db
    ports:
      - "8080:8080"
    environment:
      QUARKUS_DATASOURCE_REACTIVE_URL: postgresql://books-db:5432/books_database
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: create
      QUARKUS_DATASOURCE_USERNAME: root
      QUARKUS_DATASOURCE_PASSWORD: toor
    restart: on-failure
    networks:
      default:
        aliases:
          - books-api
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 256M
          cpus: '0.5'

